'use strict';
const questions = [
 {id:'objective',title:'What do you need to move forward?',help:'Choose the outcome that matters most right now.',options:['Prepare for a customer security review','Decide whether we are ready to launch','Review a workflow before client handoff','Understand my setup with a local scan','I’m not sure yet']},
 {id:'stage',title:'Where is your MCP setup today?',help:'Think about the setup you want to review.',options:['Exploring with a local setup','Testing a pilot','Preparing a rollout','Already live']},
 {id:'access',title:'What is the most sensitive access available?',help:'If several apply, choose the most sensitive.',options:['Sample or public data','Internal information','Customer data or production systems','I’m not sure']},
 {id:'actions',title:'Can any connected tool make changes?',help:'For example, update a record, send a message, or run a command.',options:['No, the tools are read only','Yes, but changes require approval','Yes, without approval for each change','I’m not sure']},
 {id:'timing',title:'When do you need the next decision?',help:'This helps put the first useful check in order.',options:['This week','Within 30 days','Later than 30 days','No deadline yet']}
];
const $=id=>document.getElementById(id);
const config=window.MCPScanQuizConfig||{};
const historyKey='mcpscan-funnel-v3';
const privacyVersion='2026-09-25-quiz-v1';
let answers=Array(5).fill(null),view='intro',current=0,leadReceipt=null,plan=null,submissionId=crypto.randomUUID(),previewVersion=0,requestSaved=false;
const initialSubmitLabel='Get my review plan →';
function state(){return {quiz:historyKey,view,current,answers:[...answers]};}
function track(event,details={}){document.dispatchEvent(new CustomEvent('mcpscan:quiz',{detail:{event,...details}}));}
function navigate(next,index=0){view=next;current=index;history.pushState(state(),'');render();}
function planKey(){
 const totals={enterprise:0,launch:0,agency:0,selfServe:0};
 const objective=answers[0],stage=answers[1],access=answers[2],actions=answers[3],timing=answers[4];
 if(objective===0)totals.enterprise+=5;if(objective===1)totals.launch+=5;if(objective===2)totals.agency+=5;if(objective===3)totals.selfServe+=5;
 if(stage===0)totals.selfServe+=4;if(stage===1)totals.launch+=3;if(stage===2){totals.launch+=3;totals.enterprise+=1;}if(stage===3){totals.enterprise+=3;totals.launch+=2;}
 if(access===0)totals.selfServe+=4;if(access===1){totals.launch+=3;totals.agency+=1;}if(access===2){totals.enterprise+=4;totals.launch+=2;}if(access===3){totals.launch+=2;totals.selfServe+=2;}
 if(actions===0){totals.selfServe+=2;totals.launch+=1;}if(actions===1){totals.launch+=3;totals.enterprise+=1;}if(actions===2){totals.enterprise+=4;totals.launch+=2;}if(actions===3)totals.agency+=4;
 if(timing===0){totals.launch+=3;totals.enterprise+=2;}if(timing===1)totals.launch+=3;if(timing===2)totals.agency+=4;if(timing===3)totals.selfServe+=4;
 return Object.entries(totals).sort((a,b)=>b[1]-a[1])[0][0];
}
const plans={
 enterprise:{label:'Customer or security review',name:'Prepare evidence for your security review',summary:'Your answers point to a review where someone else needs clear evidence before approving MCP access.',priority:'Document connected tools, access boundaries, and who can approve changes before sharing any sensitive details.',checks:['List MCP servers, clients, and connected systems in scope.','Separate read, write, destructive, and credential-bearing actions.','Prepare a sanitized evidence packet for the reviewer.'],sections:[{title:'Evidence to collect',body:'Start with facts a reviewer can inspect without receiving secrets.',items:['MCP server names and versions.','Connected tools and data classes.','Approval and logging boundaries.']},{title:'What to decide',body:'The decision is whether MCP access can be approved, limited, or held.',items:['Which tools need tighter permissions.','Which findings block rollout.','Which materials can be shared safely.']}],boundary:'This plan does not verify your environment. It organizes the first review path and identifies the evidence to gather.',disclaimer:'Based on your answers. Do not email credentials, private config, or customer data.',offer:'Request Enterprise Readiness scope',value:'MCPScan can turn the evidence into a fixed-scope review packet with findings, owners, and a remediation path.',cta:'Request review scope',key:'enterprise'},
 launch:{label:'Launch readiness',name:'Make your next rollout decision clearer',summary:'Your answers point to a team approaching rollout and needing a practical go or fix decision.',priority:'Confirm what each MCP tool can access and which actions need approval before the rollout expands.',checks:['Run a local scan against sanitized configuration.','Inventory connected systems and action authority.','Rank findings by launch impact and owner.'],sections:[{title:'First review pass',body:'Keep the first pass narrow enough to finish quickly.',items:['One rollout or pilot path.','The tools and systems users will actually touch.','Findings that affect launch timing.']},{title:'Decision output',body:'The useful result is a short decision packet, not a broad security report.',items:['Proceed with limits.','Fix before rollout.','Escalate for deeper review.']}],boundary:'This plan does not certify the setup. It helps identify the first review motion before rollout.',disclaimer:'Based on your answers. Use sanitized materials only.',offer:'Request Launch Audit scope',value:'MCPScan can produce a risk-ranked launch report, findings call, and re-scan path for the selected scope.',cta:'Request launch review',key:'launch'},
 agency:{label:'Client handoff',name:'Make the handoff easier to review',summary:'Your answers point to a client workflow where trust depends on a clean handoff and clear scope.',priority:'Define what was reviewed, what the workflow can change, and what remains out of scope before client handoff.',checks:['Write the client-facing scope in plain language.','List connected apps, data classes, and permitted actions.','Document unresolved findings and handoff limits.'],sections:[{title:'Handoff artifact',body:'Give the client something concrete to inspect.',items:['Reviewed workflow boundaries.','Allowed actions and approvals.','Open items with owners.']},{title:'Repeatable delivery motion',body:'Use the same pattern across clients so each workflow has a safety review before go-live.',items:['Safe intake language.','Evidence checklist.','Report and remediation summary.']}],boundary:'This plan does not approve the client workflow. It gives the first review artifact to prepare.',disclaimer:'Based on your answers. Do not send client credentials or customer data through email.',offer:'Request agency handoff review',value:'MCPScan can review a narrow client workflow and package the findings in buyer-safe language.',cta:'Request handoff review',key:'agency'},
 selfServe:{label:'Self-service baseline',name:'Start with a local baseline',summary:'Your answers point to a setup where local proof comes before a paid review.',priority:'Run a scanner baseline first, then escalate only if sensitive systems or external reviewers are involved.',checks:['Run MCPScan locally against sanitized config.','Add a CI threshold for risky findings.','Compare scanner output to the sample report format.'],sections:[{title:'Local proof path',body:'Start with evidence you can generate without sharing private material.',items:['Sanitized config scan.','Finding categories and severity.','CI gate or manual checklist.']},{title:'Escalation rule',body:'Move to paid review when the setup touches higher-risk systems or needs outside acceptance.',items:['Customer data.','Production systems.','Customer security or leadership review.']}],boundary:'This plan does not replace manual review when MCP tools can affect sensitive systems.',disclaimer:'Based on your answers. Do not upload secrets or production config.',offer:'Open the sample report first',value:'Use the sample report to understand what a paid review adds beyond scanner output.',cta:'View sample report',key:'selfServe'}
};
function derivePlan(){return plans[planKey()];}
function localResponse(payload){
 if(payload.action==='preview'){const p=derivePlan();return {preview:{key:p.key,title:p.name,summary:p.summary,priority:p.priority,contents:['Your first three priorities','Decision checks for this path','The right next move']}};}
 if(payload.action==='capture'){const p=derivePlan();return {accepted:true,receipt:{email:payload.email,answers:[...payload.answers],id:payload.submissionId},plan:p};}
 if(payload.action==='request_review'){const email=payload.receipt?.email||'';const subject=encodeURIComponent(`MCPScan review request: ${plan?.label||'Review path'}`);const body=encodeURIComponent(['MCPScan review request','',`Email: ${email}`,`Path: ${plan?.label||''}`,`Plan: ${plan?.name||''}`,'','First priorities:',...(plan?.checks||[]).map(item=>`- ${item}`),'','I am not sending secrets, credentials, customer data, or private configuration through this email.'].join('\n'));location.href=`mailto:security@getmcpscan.xyz?subject=${subject}&body=${body}`;return {accepted:true};}
 throw Error('Unsupported request.');
}
async function api(payload){
 if(!config.endpoint)return localResponse(payload);
 const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),15000);
 try{const response=await fetch(config.endpoint,{method:'POST',headers:{'Content-Type':'application/json',...config.headers},body:JSON.stringify(payload),signal:controller.signal,credentials:'omit',cache:'no-store'});let result;try{result=await response.json();}catch{throw Error('We could not save your request. Please try again.');}if(!response.ok)throw Error(result.error||'We could not save your request. Please try again.');return result;}catch(error){if(error.name==='AbortError')throw Error('The connection timed out. Your answers are still here. Please try again.');throw error;}finally{clearTimeout(timeout);}
}
function item(text,tag='li'){const node=document.createElement(tag);node.textContent=text;return node;}
function resetLead(){leadReceipt=null;plan=null;requestSaved=false;submissionId=crypto.randomUUID();}
async function showPreview(){
 const version=++previewVersion;$('capture-title').textContent='Your personalized review plan';$('capture-summary').textContent='Your priorities, the evidence to gather, and a practical next step.';$('preview-priority').textContent='Confirm what the connected tools can access before choosing your review scope.';$('preview-contents').replaceChildren(...['Your first three priorities','Checks for your next decision','Where a reviewed report adds value'].map(t=>item(t)));$('capture-error').textContent='';$('capture-submit').disabled=true;
 try{const response=await api({action:'preview',answers});if(version!==previewVersion||view!=='capture')return;const p=response.preview;if(!p?.title||!Array.isArray(p.contents))throw Error('The plan service returned an incomplete response. Please try again.');$('capture-title').textContent=p.title;$('capture-summary').textContent=p.summary;$('preview-priority').textContent=p.priority;$('preview-contents').replaceChildren(...p.contents.map(t=>item(t)));$('capture-submit').disabled=false;track('lead_gate_viewed',{path:p.key});}catch(error){if(version===previewVersion){$('capture-error').textContent=error.message;$('capture-submit').textContent='Try opening my plan again';$('capture-submit').disabled=false;}}
}
function render(focus=true){
 if(view==='result'&&!plan){view='capture';history.replaceState(state(),'');}
 const active={intro:'intro',question:'question-screen',capture:'capture-screen',result:'result-screen'}[view];
 ['intro','question-screen','capture-screen','result-screen'].forEach(id=>$(id).hidden=id!==active);
 if(view==='intro'){if(focus)$('intro-title').focus();return;}
 if(view==='question'){
  const q=questions[current];$('step-label').textContent=`Question ${current+1} of 5`;$('question-title').textContent=q.title;$('question-help').textContent=q.help;$('progress').setAttribute('aria-valuenow',current);$('progress').setAttribute('aria-valuetext',`${current} of 5 questions completed`);$('progress-fill').style.width=`${current/5*100}%`;
  $('options').replaceChildren(...q.options.map((text,index)=>{const label=document.createElement('label');label.className='option';const input=document.createElement('input');input.type='radio';input.name=q.id;input.value=index;input.checked=answers[current]===index;input.addEventListener('change',()=>{if(answers[current]!==index)resetLead();answers[current]=index;history.replaceState(state(),'');$('continue').disabled=false;});label.append(input,item(text,'span'));return label;}));
  $('continue').disabled=answers[current]===null;$('continue').textContent=current===4?'Preview my plan →':'Continue →';$('announcement').textContent=`Question ${current+1} of 5`;if(focus)$('question-title').focus();return;
 }
 if(view==='capture'){showPreview();if(focus)$('capture-title').focus();return;}
 $('result-label').textContent=plan.label;$('result-title').textContent=plan.name;$('result-reason').textContent=plan.summary;$('checklist').replaceChildren(...plan.checks.map(t=>item(t)));
 $('plan-sections').replaceChildren(...plan.sections.map(s=>{const section=document.createElement('section');section.className='plan-section';const ul=document.createElement('ul');ul.append(...s.items.map(t=>item(t)));section.append(item(s.title,'h3'),item(s.body,'p'),ul);return section;}));
 $('plan-boundary').textContent=plan.boundary;$('plan-disclaimer').textContent=plan.disclaimer;$('offer-title').textContent=plan.offer;$('offer-value').textContent=plan.value;$('request-review').textContent=requestSaved?'Review requested':plan.cta;$('request-review').disabled=requestSaved;$('review-status').textContent=requestSaved?'Your review request is saved. MCPScan can use your answers to confirm scope and next steps.':'';$('review-error').textContent='';$('status').textContent='';if(focus)$('result-title').focus();
}
$('start').addEventListener('click',()=>{track('quiz_started');navigate('question',0);});
$('question-form').addEventListener('submit',e=>{e.preventDefault();if(answers[current]===null)return;track('question_completed',{question:questions[current].id});if(current<4)navigate('question',current+1);else navigate(plan?'result':'capture',4);});
$('back').addEventListener('click',()=>navigate(current===0?'intro':'question',Math.max(0,current-1)));
$('capture-back').addEventListener('click',()=>navigate('question',4));$('edit').addEventListener('click',()=>navigate('question',0));
$('restart').addEventListener('click',()=>{answers=Array(5).fill(null);resetLead();$('lead-email').value='';navigate('intro');});
$('capture-form').addEventListener('submit',async e=>{
 e.preventDefault();if(!$('capture-form').reportValidity())return;$('capture-submit').disabled=true;$('capture-submit').textContent='Opening your plan…';$('capture-error').textContent='';const submittedAnswers=JSON.stringify(answers);track('lead_submit_started');
 try{const response=await api({action:'capture',email:$('lead-email').value.trim(),answers,privacyVersion,submissionId,website:$('website').value});if(!response.accepted||!response.receipt||!response.plan)throw Error('We could not confirm your request. Please try again.');if(submittedAnswers!==JSON.stringify(answers))return;leadReceipt=response.receipt;plan=response.plan;track('lead_captured',{path:plan.key});if(view==='capture'){navigate('result',4);track('artifact_viewed',{path:plan.key});}}catch(error){$('capture-error').textContent=error.message;track('lead_capture_failed');}finally{$('capture-submit').disabled=false;$('capture-submit').textContent=initialSubmitLabel;}
});
$('request-review').addEventListener('click',async()=>{
 if(!leadReceipt||requestSaved)return;$('request-review').disabled=true;$('request-review').textContent='Saving your request…';$('review-error').textContent='';
 try{const response=await api({action:'request_review',receipt:leadReceipt});if(!response.accepted)throw Error('We could not confirm your request. Please try again.');requestSaved=true;$('request-review').textContent='Review requested';$('review-status').textContent='Your review request is saved. MCPScan can use your answers to confirm scope and next steps.';track('review_requested',{path:plan.key});}catch(error){$('review-error').textContent=error.message;$('request-review').disabled=false;$('request-review').textContent=plan.cta;}
});
function planText(){return ['MCPScan',plan.name,'',plan.reason,'','YOUR FIRST THREE PRIORITIES',...plan.checks.map((s,i)=>`${i+1}. ${s}`),'',...plan.sections.flatMap(s=>[s.title,s.body,...s.items.map(t=>'- '+t),'']),'WHERE THIS PLAN STOPS',plan.boundary,'',plan.offer,plan.value,'Next step: Return to your open plan and select "'+plan.cta+'" to request a scoped review.','',plan.disclaimer].join('\n');}
$('download').addEventListener('click',()=>{if(!plan||!leadReceipt)return;const url=URL.createObjectURL(new Blob([planText()],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=plan.name.replace(/[^a-zA-Z0-9]+/g,'-')+'.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$('status').textContent='Your full plan download has started.';track('artifact_downloaded',{path:plan.key});});
$('print-plan').addEventListener('click',()=>{if(plan){track('artifact_printed',{path:plan.key});window.print();}});
window.addEventListener('popstate',e=>{const s=e.state;if(s?.quiz!==historyKey)return;if(JSON.stringify(answers)!==JSON.stringify(s.answers))resetLead();({view,current,answers}=s);render();});
if(history.state?.quiz===historyKey)({view,current,answers}=history.state);else history.replaceState(state(),'');render(false);
